# Generated by Django 3.1.4 on 2020-12-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
